//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSearch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gg,https://www.google.com,/search?q=,SEP=+")]
        public string SEARCHgg {
            get {
                return ((string)(this["SEARCHgg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imdb,http://www.imdb.com,/find/?q=,SEP=+")]
        public string SEARCHimdb {
            get {
                return ((string)(this["SEARCHimdb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("map,https://www.google.com,/maps/search/,SEP=+")]
        public string SEARCHmap {
            get {
                return ((string)(this["SEARCHmap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("so,https://www.stackoverflow.com,/search?q=,SEP=+")]
        public string SEARCHso {
            get {
                return ((string)(this["SEARCHso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wik,http://www.wikipedia.org,/wiki/Special:Search/,SEP=_")]
        public string SEARCHwik {
            get {
                return ((string)(this["SEARCHwik"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("you,https://www.youtube.com,/results?search_query=,SEP=+")]
        public string SEARCHyou {
            get {
                return ((string)(this["SEARCHyou"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("amaz,http://www.amazon.com,/s/?keywords=,SEP=%20")]
        public string SEARCHamaz {
            get {
                return ((string)(this["SEARCHamaz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flix,https://www.netflix.com,/search/,SEP=%20")]
        public string SEARCHflix {
            get {
                return ((string)(this["SEARCHflix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nyt,http://query.nytimes.com,/search/sitesearch/?action=click&contentCollection&r" +
            "egion=TopBar&WT.nav=searchWidget&module=SearchSubmit&pgtype=Homepage#/,SEP= ")]
        public string SEARCHnyt {
            get {
                return ((string)(this["SEARCHnyt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ev,c:\\program files\\everything\\everything.exe ,,PARM=-s \"$\"")]
        public string SEARCHev {
            get {
                return ((string)(this["SEARCHev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("urb,http://www.urbandictionary.com,/define.php?term=,SEP=+")]
        public string SEARCHurb {
            get {
                return ((string)(this["SEARCHurb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dic,https://www.merriam-webster.com,/dictionary/,SEP=%20")]
        public string SEARCHdic {
            get {
                return ((string)(this["SEARCHdic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iexplore.exe")]
        public string Browser {
            get {
                return ((string)(this["Browser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int OffsetHeight {
            get {
                return ((int)(this["OffsetHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OffsetWidth {
            get {
                return ((int)(this["OffsetWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wf,http://www.wellsfargo.com,,")]
        public string SEARCHwf {
            get {
                return ((string)(this["SEARCHwf"]));
            }
        }
    }
}
